### ISSUE TITLE
[BUG]  p is not defined

### ISSUE THREAD

**Issue by Em1tt** [b1tt0/tinyhost#2]
Upon running tinyhost from my machine (Windows 10), it throws a "p is not defined"

here's the code I'm using:

```js
const th = require("tinyhost")(3000, null, false);

th.req("/", (req, res) => res.write("Hello"), "GET");
```

here's the full error

```
    server = p ? https() : http();
    ^

ReferenceError: p is not defined
    at open (E:\GitHub_Repositories\Personal\tinyhostbackend\node_modules\tinyhost\index.js:41:5)
    at module.exports (E:\GitHub_Repositories\Personal\tinyhostbackend\node_modules\tinyhost\index.js:116:3)
    at Object.<anonymous> (E:\GitHub_Repositories\Personal\tinyhostbackend\index.js:1:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Em1tt** [comment]
I am using the version 2.1.1

**Comment by b1tt0** [comment]
fixed in 3634c13

**Comment by Em1tt** [comment]
@b1tt0 this commit created another issue, which is this:

```
  if (!cb) throw new Error("Undefined callback.");
  ^

ReferenceError: cb is not defined
    at Object.req (E:\GitHub_Repositories\Personal\tinyhostbackend\node_modules\tinyhost\index.js:93:3)
    at Object.<anonymous> (E:\GitHub_Repositories\Personal\tinyhostbackend\index.js:3:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by b1tt0** [comment]
8275ed3
